### ISSUE TITLE
WP API Search not working

### ISSUE THREAD

**Issue by BigActual** [disAbility-Connections/ion-ap3-child#10]

**Comment by d4mation** [comment]
Details: 

Choosing a County like Lenawee and then Searching for "Pizza" seems to show unrelated results.

> So, here’s Pizza in Lenawee.
> 
> The results are the same as in the App, so something is screwy on the WP-side. I checked the first result, Boot Jack Tavern, for any Tags or anything that could be getting it to come back as “pizza” and nothing matches up.
> 
> https://disabilityconn.wpengine.com/wp-json/wp/v2/posts?categories=4238&search=pizza

**Comment by d4mation** [comment]
It seems that for some reason, it isn't placing enough importance on what is in the Post Title and Post Content and that if nothing matches, it still keeps a Post in the result.

For example, Lenawee County, searching "Coffee"
https://disabilityconn.wpengine.com/wp-json/wp/v2/posts?categories=4238&search=coffee

This Tag can be found in the first result, which is "Coffee"
https://disabilityconn.wpengine.com/wp-json/wp/v2/tags/1524

In this case, it is in the Post Title and it is a Tag. When searching for Pizza, there are Posts with "Pizza" in the name, but they show lower than Boot Jack Tavern, which doesn't match the search at all.

**Comment by d4mation** [comment]
After some good old Rubber Duck Debugging, I believe I just found out why searching for “Pizza” is broken.

“Pizza” is in the Category Description for Lenawee County. And probably the Category Description of the others as well.

Therefore, every Post in that Category is technically a match for “Pizza”.

I'll see if I can find out a way to exclude Category Descriptions from the REST API Searches, as they aren't relevant to the App.

https://disabilityconn.wpengine.com/wp-json/wp/v2/categories/4238

**Comment by d4mation** [comment]
This is because of the "Search Everything" plugin that is active on the site. It oddly does not cause the problem on the website itself (although looking at the code, it should), but it is forcing into the SQL Query that is generated when the site gets a Search Request an additional check against the Category Name _and Category Description_. 

I tried to see if there was a good way for me to disable just checking the Category Description for the App via this Child Theme, but unfortunately due to some of the design decisions of the plugin this is not possible. 

The plugin has been abandoned for the past few year or so, so even if I were to request adding this feature it would likely not happen: https://wordpress.org/support/topic/search-everything-support-update/

Perhaps a different searching plugin should be used, given that this one is no longer receiving support anyway?

**Comment by BigActual** [comment]
Understood. Per the discussion offline between Eric and I, we will switch to Relevansi, a solid alternative that is supported well.

**Comment by d4mation** [comment]
Switched over and it appears to be working correctly now. Closing.
