### ISSUE TITLE
Fix being able to stay in a county if a person presses back and is at home screen

### ISSUE THREAD

**Issue by BigActual** [disAbility-Connections/ion-ap3-child#7]
When you pick a county then hit the back button to go back to the Home screen you cannot select that county again.  You have to go up to the “hamburger” and select the county from there.

**Comment by d4mation** [comment]
I'll have to see if there's a way to force it to "forget" which was the last chosen County. This is happening because a "change" isn't happening on the Dropdown to force it to redirect.

**Comment by BigActual** [comment]
Please proceed.

**Comment by BigActual** [comment]
To clarify. The team can't go back to the same county. They have to select another county and then select the first county again.

**Comment by d4mation** [comment]
Yes, I can see the problem. I'm unfortunately having a difficult time finding a fix for it however.

**Comment by d4mation** [comment]
I've researched this a lot and there are two main problems that seem to crop up each time:

1. It seems that they never technically "leave" the home page. Rather, a new page is overlaid on top of it, almost like going to a new tab. This is likely why the value isn't just clearing out on its own (Since I am implementing nothing which should be saving it).
2. Ionic (which AppPresser uses) has events for "onChange" and "onCancel" for Select fields. The "onChange" event unfortunately does not fire off if they click "Ok" without actually changing the value. 
    - The only way to correct this that I can see is to use some custom JavaScript code, but this JavaScript code needs to be able to access all the Angular stuff that Ionic (and AppPresser, by extension) use behind-the-scenes, which they don't seem to expose in any way.

I'm going to try reaching out to AppPresser support to see if there's any way to force-clear the value after directing them to a new page that I'm missing. Unless there's some way to do this, this may be something that would require building the app ourselves.

**Comment by d4mation** [comment]
This has been miraculously solved.

`<ion-select id="county-select" #countySelect (ionChange)="pushPage($event);countySelect.value=null">`

I'm not sure of how the syntax works here fully, but it does. AppPresser support has been fantastic.
